# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    services.car:
        class: Huoltoaika\Service\CarService
        arguments: ["@doctrine.orm.default_entity_manager"]

    services.booking:
        class: Huoltoaika\Service\BookingService
        arguments: ["@doctrine.orm.default_entity_manager"]

    services.person:
        class: Huoltoaika\Service\PersonService
        arguments: ["@doctrine.orm.default_entity_manager"]
